export type FieldType = 'text' | 'number' | 'select' | 'checkbox';

export interface CategoryField {
  id: string;
  label: string;
  type: FieldType;
  options?: string[]; // Used for 'select' type
}

export const CATEGORY_FIELDS: Record<string, CategoryField[]> = {
  restaurants: [
    { id: 'cuisineType', label: 'Vrsta kuhinje', type: 'select', options: ['Mediteranska', 'Tradicionalna', 'Riblja', 'Fast Food', 'Pizzeria', 'Fine Dining', 'Internacionalna'] },
    { id: 'hasDelivery', label: 'Mogućnost dostave', type: 'checkbox' },
    { id: 'dressCode', label: 'Dress Code', type: 'select', options: ['Ležerno', 'Smart Casual', 'Formalno'] },
    { id: 'vegetarianOptions', label: 'Vegetarijanske/Veganske opcije', type: 'checkbox' },
    { id: 'petFriendly', label: 'Pet Friendly', type: 'checkbox' },
    { id: 'outdoorSeating', label: 'Terasa / Vanjski prostor', type: 'checkbox' },
    { id: 'reservationRecommended', label: 'Preporuka za rezervaciju', type: 'checkbox' },
    { id: 'michelin', label: 'Michelin preporuka', type: 'checkbox' },
  ],
  hotels: [
    { id: 'stars', label: 'Broj zvjezdica', type: 'select', options: ['1', '2', '3', '4', '5'] },
    { id: 'hasPool', label: 'Bazen', type: 'checkbox' },
    { id: 'hasSpa', label: 'Spa i Wellness', type: 'checkbox' },
    { id: 'hasParking', label: 'Besplatan Parking', type: 'checkbox' },
    { id: 'checkInTime', label: 'Vrijeme prijave (Check-in)', type: 'text' },
    { id: 'checkOutTime', label: 'Vrijeme odjave (Check-out)', type: 'text' },
    { id: 'freeWifi', label: 'Besplatan WiFi', type: 'checkbox' },
    { id: 'breakfastIncluded', label: 'Doručak uključen u cijenu', type: 'checkbox' },
    { id: 'petFriendly', label: 'Pet Friendly', type: 'checkbox' },
    { id: 'gym', label: 'Teretana / Fitness', type: 'checkbox' },
    { id: 'accessible', label: 'Prilagođeno osobama s invaliditetom', type: 'checkbox' },
  ],
  bars: [
    { id: 'barType', label: 'Vrsta bara', type: 'select', options: ['Beach Bar', 'Lounge Bar', 'Caffe Bar', 'Pub', 'Wine Bar'] },
    { id: 'hasHappyHour', label: 'Happy Hour', type: 'checkbox' },
    { id: 'hasLiveMusic', label: 'Živa glazba', type: 'checkbox' },
    { id: 'foodOffered', label: 'Ponuda hrane / Snackovi', type: 'checkbox' },
    { id: 'shisha', label: 'Shisha / Nargila', type: 'checkbox' },
    { id: 'seaView', label: 'Pogled na more', type: 'checkbox' },
    { id: 'petFriendly', label: 'Pet Friendly', type: 'checkbox' },
  ],
  nightclubs: [
    { id: 'musicGenre', label: 'Glavni žanr glazbe', type: 'select', options: ['House/Techno', 'Komercijalna', 'Domaća', 'R&B/Hip-Hop', 'Razno'] },
    { id: 'entryFee', label: 'Naplaćuje se ulaz', type: 'checkbox' },
    { id: 'vipTables', label: 'VIP Stolovi', type: 'checkbox' },
    { id: 'ageLimit', label: 'Dobna granica', type: 'select', options: ['Nema', '18+', '21+'] },
    { id: 'wardrobe', label: 'Garderoba', type: 'checkbox' },
    { id: 'dressCode', label: 'Dress Code', type: 'select', options: ['Nema', 'Smart Casual', 'Formalno'] },
  ],
  boat_rentals: [
    { id: 'boatTypes', label: 'Vrste plovila u ponudi', type: 'text' },
    { id: 'licenseRequired', label: 'Potrebna dozvola', type: 'checkbox' },
    { id: 'skipperAvailable', label: 'Mogućnost najma skipera', type: 'checkbox' },
    { id: 'fuelIncluded', label: 'Gorivo uključeno u cijenu', type: 'checkbox' },
    { id: 'snorkelingGear', label: 'Oprema za ronjenje uključena', type: 'checkbox' },
    { id: 'maxPersons', label: 'Maksimalan broj osoba', type: 'number' },
    { id: 'petFriendly', label: 'Dozvoljeni kućni ljubimci', type: 'checkbox' },
  ],
  rent_a_car: [
    { id: 'vehicleTypes', label: 'Vrste vozila', type: 'text' },
    { id: 'depositRequired', label: 'Potreban depozit', type: 'checkbox' },
    { id: 'insuranceIncluded', label: 'Osiguranje uključeno', type: 'checkbox' },
    { id: 'minAge', label: 'Minimalna dob vozača', type: 'number' },
    { id: 'transmission', label: 'Prijenos', type: 'select', options: ['Automatik', 'Manual', 'Oboje'] },
    { id: 'unlimitedMileage', label: 'Neograničena kilometraža', type: 'checkbox' },
    { id: 'deliveryToAddress', label: 'Dostava vozila na adresu', type: 'checkbox' },
  ],
  tours: [
    { id: 'tourDuration', label: 'Trajanje izleta', type: 'select', options: ['Do 2 sata', 'Pola dana', 'Cijeli dan', 'Višednevno'] },
    { id: 'tourDifficulty', label: 'Težina izleta', type: 'select', options: ['Lagano', 'Srednje', 'Teško'] },
    { id: 'languages', label: 'Jezici vodiča', type: 'text' },
    { id: 'familyFriendly', label: 'Prikladno za djecu', type: 'checkbox' },
    { id: 'groupSize', label: 'Veličina grupe', type: 'select', options: ['Privatno', 'Mala grupa', 'Velika grupa'] },
    { id: 'foodIncluded', label: 'Hrana i piće uključeni', type: 'checkbox' },
    { id: 'equipmentIncluded', label: 'Oprema uključena', type: 'checkbox' },
  ],
  wellness: [
    { id: 'wellnessServices', label: 'Glavne usluge (Masaža, Sauna...)', type: 'text' },
    { id: 'reservationRequired', label: 'Obavezna rezervacija', type: 'checkbox' },
    { id: 'couplesMassage', label: 'Masaža za parove', type: 'checkbox' },
    { id: 'medicalTreatments', label: 'Medicinski tretmani', type: 'checkbox' },
    { id: 'poolJacuzzi', label: 'Bazen / Jacuzzi', type: 'checkbox' },
  ],
  culture: [
    { id: 'institutionType', label: 'Vrsta ustanove', type: 'select', options: ['Muzej', 'Galerija', 'Kazalište', 'Kino', 'Spomenik'] },
    { id: 'guidedTours', label: 'Grupni vodič', type: 'checkbox' },
    { id: 'studentDiscount', label: 'Studentski popust', type: 'checkbox' },
    { id: 'audioGuide', label: 'Audio vodič', type: 'checkbox' },
    { id: 'accessible', label: 'Prilagođeno osobama s invaliditetom', type: 'checkbox' },
  ],
  shops: [
    { id: 'shopType', label: 'Vrsta trgovine', type: 'select', options: ['Suveniri', 'Odjeća i obuća', 'Nakit', 'Lokalni proizvodi', 'Mješovita roba'] },
    { id: 'localProducts', label: 'Prodaja autohtonih proizvoda', type: 'checkbox' },
    { id: 'taxFree', label: 'Tax Free', type: 'checkbox' },
    { id: 'delivery', label: 'Mogućnost dostave na adresu', type: 'checkbox' },
    { id: 'handmade', label: 'Ručni rad / Hand-made', type: 'checkbox' },
  ],
  mechanics: [
    { id: 'towingService', label: 'Vučna služba (0-24)', type: 'checkbox' },
    { id: 'replacementVehicle', label: 'Zamjensko vozilo', type: 'checkbox' },
    { id: 'repairTypes', label: 'Vrste popravaka', type: 'text' },
    { id: 'bodywork', label: 'Autolimarija i lakiranje', type: 'checkbox' },
    { id: 'tires', label: 'Vulkanizer / Gume', type: 'checkbox' },
    { id: 'diagnostics', label: 'Auto-dijagnostika', type: 'checkbox' },
  ],
  it: [
    { id: 'softwareDev', label: 'Razvoj softvera', type: 'checkbox' },
    { id: 'hardwareSupport', label: 'Održavanje opreme', type: 'checkbox' },
    { id: 'fieldWork', label: 'Terenski rad', type: 'checkbox' },
    { id: 'emergencySupport', label: 'Hitne intervencije (24/7)', type: 'checkbox' },
    { id: 'networksServers', label: 'Mreže i serveri', type: 'checkbox' },
  ],
  marketing: [
    { id: 'seo', label: 'SEO Optimizacija', type: 'checkbox' },
    { id: 'socialMedia', label: 'Vođenje društvenih mreža', type: 'checkbox' },
    { id: 'videoProd', label: 'Video produkcija', type: 'checkbox' },
    { id: 'ads', label: 'Google i Meta Oglasi', type: 'checkbox' },
    { id: 'pr', label: 'PR Usluge', type: 'checkbox' },
  ],
  digital: [
    { id: 'webDesign', label: 'Web dizajn', type: 'checkbox' },
    { id: 'hosting', label: 'Web Hosting', type: 'checkbox' },
    { id: 'graphicDesign', label: 'Grafički dizajn', type: 'checkbox' },
    { id: 'uiUx', label: 'UI/UX Dizajn', type: 'checkbox' },
    { id: 'mobileApps', label: 'Razvoj mobilnih aplikacija', type: 'checkbox' },
  ],
  accounting: [
    { id: 'taxConsulting', label: 'Porezno savjetovanje', type: 'checkbox' },
    { id: 'annualReports', label: 'Izrada završnog računa', type: 'checkbox' },
    { id: 'payroll', label: 'Obračun plaća', type: 'checkbox' },
    { id: 'companyFormation', label: 'Usluge osnivanja tvrtke', type: 'checkbox' },
  ],
  hairdressers: [
    { id: 'salonType', label: 'Tip salona (Muški/Ženski)', type: 'select', options: ['Muški', 'Ženski', 'Unisex'] },
    { id: 'barber', label: 'Barber usluge', type: 'checkbox' },
    { id: 'hairColoring', label: 'Bojanje kose', type: 'checkbox' },
    { id: 'weddingHair', label: 'Svečane frizure / Vjenčanja', type: 'checkbox' },
    { id: 'extensions', label: 'Ugradnja ekstenzija', type: 'checkbox' },
  ],
  beauty: [
    { id: 'massage', label: 'Masaža', type: 'checkbox' },
    { id: 'nails', label: 'Nokti (Manikura/Pedikura)', type: 'checkbox' },
    { id: 'depilation', label: 'Depilacija', type: 'checkbox' },
    { id: 'makeup', label: 'Šminkanje / Make-up', type: 'checkbox' },
    { id: 'facial', label: 'Tretmani lica', type: 'checkbox' },
    { id: 'laserHairRemoval', label: 'Laserska epilacija', type: 'checkbox' },
  ],
};
